### ISSUE TITLE
Outdated ECS Anywhere Installation Script

### ISSUE THREAD

**Issue by hrko** [aws-samples/amazon-ecs-anywhere-cdk-samples#5]
https://github.com/aws-samples/amazon-ecs-anywhere-cdk-samples/blob/230fe0a87a8d306f89a5534ec91be5332841d1d3/cdk/lib/EcsAnywhereStack.ts#L79

This project uses the old ECS Anywhere installation script. This script has problems such as not supporting cgroup v2, etc. and needs to be replaced with a new script URL.
Here is the new URL: `https://amazon-ecs-agent.s3.amazonaws.com/ecs-anywhere-install-latest.sh`

See also: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere-registration.html

**Comment by Dr-Rahul-Gaikwad** [comment]
Fixed. Thanks!
